# Generated by Django 2.0.12 on 2020-11-19 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20201119_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='mob',
            field=models.CharField(default='9847563210', max_length=200),
        ),
    ]
