# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-11-11 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stafc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('cat', models.CharField(max_length=200)),
                ('dob', models.DateField(max_length=200)),
                ('dep', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('status', models.IntegerField(default=2)),
                ('approve', models.IntegerField(default=0)),
                ('role', models.CharField(max_length=200)),
            ],
        ),
    ]
