# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-11-11 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=200)),
                ('drole', models.CharField(max_length=200)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
    ]
