# Generated by Django 2.0.12 on 2020-11-19 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('username', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('status', models.IntegerField(default=0)),
                ('role', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='role',
        ),
        migrations.DeleteModel(
            name='stafc',
        ),
    ]
